### ISSUE TITLE
Create Additional Assets

### ISSUE THREAD

**Issue by Alice-Jaffray** [ConorMFinn/CO600-SeriousCyberSec#55]
## Expected Behaviour
Assets for the rest of the house:

- [ ] Bookcase
- [ ] Dining table
- [ ] Flower pot
- [ ] Sofa
- [ ] Cardboard box
- [ ] Portrait
- [ ] Server towers

## Actual Behaviour
Assets are missing

**Comment by cailafinn** [comment]
Just noticed this seems to be a duplicate of #56
